# FE : reactJs
# BE : Spring boot
# DB : Postgres
# Cloud : AWS
# CI/CD : Github Actions

version: "3.8"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jimechuuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jimechu
    networks:
      - jimechu

  backend:
    image: spring-boot-app
    build:
      context: ./backend/jimechu
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/jimechu"
      SPRING_DATASOURCE_USERNAME: jimechuuser
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - jimechu

  # frontend:
  #   image: react-app
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - jimechu

volumes:
  postgres_data: {}

networks:
  jimechu:
    driver: bridge
