spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/jimechu
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:jimechu}
    username: ${RDS_USERNAME:jimechuuser}
    password: ${RDS_PASSWORD:postgres}
    #    driver-class-name: org.h2.Driver
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  #        format_sql: true

  security:
    user:
      password: test
    filter:
      order: 10

logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: DEBUG
  jiandgyu.jimechu.service: debug
  jiandgyu.jimechu.config.security: DEBUG

  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

# Swagger
springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret-key: Nlrb9F775ImlbjellXgxmGrgran60crFCeTvIjAJ3G1rfePs0XY22aq0MJ9WU9lyLoqeORjNcQlxgFuIalfq4w==
  expiration-time: 86400000 #1일
